Repository Developer-Student-Clubs-VSSUT-Burla/Master-PyAlgo, pull requests merged in 2021-03, with the labels that each got.

#56 [GSSOC'21] Added Sorting algorithm implementation in python #24
  Algorithms/Sorting/Sorting_Algorithms_Implementation.py
Labels: Level 1, gssoc21

#75 added maximim and minimum of array
  Topic Wise Questions with Solutions/Array/max_min.py
Labels: good first issue, gssoc21, level 0

#88 Added solution to a strings problem
  String/Chech_if_string_contains_all_Binar_codes_of_size_k/check_for_all_binary_codes.py
  String/Chech_if_string_contains_all_Binar_codes_of_size_k/readme.txt
Labels: gssoc21, level 0

#57 Bubble sort
  Sorting Algorithms/bubblesort.py
Labels: gssoc21, level 0

#97 Added LCS
  Dynamic Programming/Longest_Common_SubSequence.py
Labels: gssoc21, level 0

#113 fixes issue-65
  String/Reverse_String_Variation/readme.txt
  String/Reverse_String_Variation/solution.py
Labels: gssoc21, level 0

#76 Checking strings are Anagram or not. (#55)
  String/Checking_Anagrams.py
Labels: gssoc21, level 0, requested changes

#121 Pangram added
  String/check_pangram.py
Labels: gssoc21, level 0

#91 Palindrome using doubly linked list
  Topic Wise Questions with Solutions/Linked List/doublylinkedlist-palindrome.py
Labels: gssoc21, level 0, requested changes

#100 [Issue-80] Implements the sorting of 0s 1s 2s
  Topic Wise Questions with Solutions/Array/sort_012.py
Labels: gssoc21, level 0

#115 binarysearch added
  Algorithms/Searching/binarysearch_recursion.py
Labels: changes requested

#125 Added Linear Search #93
  Algorithms/Searching/linear_search.py
Labels: changes requested

#139 fix driver function.
  Topic Wise Questions with Solutions/Array/move_negative_before_positive.py
Labels: gssoc21, level 0

#112 Index
  Topic Wise Questions with Solutions/Array/reverse_array.py
Labels: gssoc21, level 0

#225 Added shell_sort.py
  Algorithms/Sorting/shell_sort.py
Labels: changes requested

#123 Sieve_Of_Atkins(#89)
  Algebra/Sieve_Of_Atkins.py
Labels: gssoc21, level 0

#135 Union and Intersection of sorted arrays
  Topic Wise Questions with Solutions/Array/intersection_sortedarray.py
  Topic Wise Questions with Solutions/Array/union_sortedarrays.py
Labels: gssoc21, level 0

#147 Implemented Binary Search Tree wtih Standard Problems
  Data Structures/Binary_Search_Tree.py
  Topic Wise Questions with Solutions/Binary_Search_Tree/maximum_minimum_BST.py
Labels: Level 1, gssoc21

#166 Neon number added
  Numerical/neon.py
Labels: gssoc21, level 0

#174 Added Rabin-Karp string searching algorithm (Issue #98)
  README.md
  String/RabinKarpStringMatching.py
Labels: gssoc21, level 0

#224 adding climbing stairs
  Dynamic Programming/climbing_stairs.py
Labels: gssoc21, level 0

#190 Length of last word program added
  String/length_of_last_word.py
Labels: gssoc21, level 0

#199 Queue Implementation
  Data Structures/Queue.py
Labels: gssoc21, level 0

#209 Euclidian Algorithm for finding GCD
  Algebra/Euclid_algo_GCD.py
Labels: gssoc21, level 0

#230 Trailing zeroes
  Numerical/Trailing_Zeroes.py
Labels: changes requested

#246 Added Magic Number
  Algebra/Magic_Number.py
Labels: changes requested
