Repository Developer-Student-Clubs-VSSUT-Burla/Master-PyAlgo, pull requests merged in 2021-06, with the labels that each got.

#470 Added n queens
  Topic Wise Questions with Solutions/Recursion/N-Queen.py
Labels: changes requested

#366 Added the required code
  Topic Wise Questions with Solutions/Linked List/remove.py
Labels: Level2, gssoc21

#421 Issue 378
  Topic Wise Questions with Solutions/Array/Get_Max.py
Labels: changes requested

#494 added fractional knapsack
  greedy algorithms/fractional_knapsack.py
Labels: changes requested

#478 add Topic Wise Questions with Solutions/Array/Minimize_the_Heights.py
  Topic Wise Questions with Solutions/Array/Minimize_the_Heights.py
Labels: changes requested

#515 Level Order Traversal of BST
  Topic Wise Questions with Solutions/Binary_Search_Tree/BST_Level_Order_Traversal.py
Labels: GSSoC21

#529 Leap Year Checker
  Algebra/Leap_Year.py
Labels: GSSoC21

#516 Removing Duplicates from Linked List
  Topic Wise Questions with Solutions/Linked List/Removing_Duplicacies.py
Labels: GSSoC21

#534 Swap Case
  String/Swap_Case.py
Labels: GSSoC21

#499 Added Program for 'Valid Powers'
  Algebra/Valid_Powers.py
Labels: GSSoC21

#532 Square of Numbers
  Algebra/Square_of_Numbers.py
Labels: GSSoC21
